=== diva-exchange/divachain/dist/schema/block/v3/block.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "/schema/block/v3/block.json",

  "type": "object",
  "properties": {
    "version": {
      "type": "integer",
      "minimum": 3,
      "maximum": 3
    },
    "previousHash": {
      "type": "string",
      "pattern": "^[A-Za-z0-9_-]{43}$"
    },
    "hash": {
      "type": "string",
      "pattern": "^[A-Za-z0-9_-]{43}$"
    },
    "tx": {
      "type": "array",
      "items": {
        "$ref": "transaction/tx.json"
      },
      "minItems": 1,
      "uniqueItems": true
    },
    "height": {
      "type": "integer",
      "minimum": 1
    },
    "votes": {
      "type": "array",
      "items": {
        "$ref": "votes.json"
      },
      "uniqueItems": true
    }
  },
  "required": [
    "version",
    "previousHash",
    "hash",
    "tx",
    "height",
    "votes"
  ],
  "additionalProperties": false
}

=== diva-exchange/divachain/genesis/block.v7.json
{
  "version": 7,
  "previousHash": "0000000000000000000000000000000000000000000",
  "hash": "0000000000000000000000000000000000000000000",
  "tx": [
    {
      "ident": "genesis",
      "origin": "0000000000000000000000000000000000000000000",
      "commands": [
        {
          "seq": 1,
          "command": "data",
          "ns": "genesis:init",
          "d": ""
        }
      ],
      "sig": "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
    }
  ],
  "height": 1,
  "votes": [
    {
      "origin": "0000000000000000000000000000000000000000000",
      "sig": "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
    }
  ]
}
