=== diva-exchange/divachain/dist/schema/schema/tx/v1/tx.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "/schema/tx/v1/tx.json",

  "type": "object",
  "properties": {
    "v": {
      "type": "integer",
      "minimum": 1,
      "maximum": 1
    },
    "height": {
      "type": "integer",
      "minimum": 1
    },
    "origin": {
      "type": "string",
      "pattern": "^[A-Za-z0-9_-]{43}$"
    },
    "hash": {
      "type": "string",
      "pattern": "^[A-Za-z0-9_-]{43}$"
    },
    "prev": {
      "type": "string",
      "pattern": "^[A-Za-z0-9_-]{43}$"
    },
    "commands": {
      "type": "array",
      "items": {
        "anyOf": [
          {
            "$ref": "add-peer.json"
          },
          {
            "$ref": "remove-peer.json"
          },
          {
            "$ref": "modify-stake.json"
          },
          {
            "$ref": "data.json"
          }
        ]
      },
      "minItems": 1,
      "maxItems": 32,
      "uniqueItems": true
    },
    "votes": {
      "$ref": "votes.json"
    }
  },
  "required": [
    "v",
    "height",
    "origin",
    "hash",
    "prev",
    "commands",
    "votes"
  ],
  "additionalProperties": false
}

=== diva-exchange/divachain/genesis/tx.v1.json
{
  "v": 1,
  "height": 1,
  "prev": "0000000000000000000000000000000000000000000",
  "hash": "0000000000000000000000000000000000000000000",
  "origin": "0000000000000000000000000000000000000000000",
  "commands": [
    {
      "seq": 1,
      "cmd": "data",
      "ns": "genesis:init",
      "d": ""
    }
  ],
  "votes": [
    {
      "origin": "0000000000000000000000000000000000000000000",
      "sig": "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
    }
  ]
}
